import { stripComments } from './src/comment-stripper.js';
import { getProfiles, detectLanguageByContent, detectLanguageByFilename } from './src/languages.js';

const codeInput=document.querySelector('#codeInput');const output=document.querySelector('#outputCode');const languageSelect=document.querySelector('#languageSelect');const fileInput=document.querySelector('#fileInput');const fileName=document.querySelector('#fileName');const stats=document.querySelector('#stats');const whitespaceToggle=document.querySelector('#trimWhitespace');const wrapToggle=document.querySelector('#wrapText');const copyInputButton=document.querySelector('#copyInputButton');const copyButton=document.querySelector('#copyButton');const downloadButton=document.querySelector('#downloadButton');const swapButton=document.querySelector('#swapButton');const clearButton=document.querySelector('#clearButton');const themeButton=document.querySelector('#themeButton');
function loadLanguages(){languageSelect.innerHTML='<option value="auto">Auto detect</option>'+getProfiles().filter(p=>p.id!=='generic').map(p=>`<option value="${p.id}">${p.name}</option>`).join('');}
function lineCount(value){return value.length?value.split(/\r\n|\r|\n/).length:0;}
function process(){const selected=languageSelect.value;const language=selected==='auto'?detectLanguageByContent(codeInput.value):selected;let result=stripComments(codeInput.value,language);if(whitespaceToggle.checked)result=result.replace(/^[ \t]+$/gm,'').replace(/\n{3,}/g,'\n\n');output.value=result;const removed=Math.max(0,codeInput.value.length-result.length);const inputLines=lineCount(codeInput.value);const outputLines=lineCount(result);stats.textContent=`${language} · ${removed.toLocaleString()} chars removed · ${inputLines} → ${outputLines} lines`;}
function readFile(file){const reader=new FileReader();reader.onload=()=>{codeInput.value=String(reader.result||'');fileName.textContent=file.name;const detected=detectLanguageByFilename(file.name);languageSelect.value=detected==='generic'?'auto':detected;process();};reader.readAsText(file);}
async function copyText(value,button,label){await navigator.clipboard.writeText(value);const original=button.textContent;button.textContent=label;setTimeout(()=>{button.textContent=original;},1200);}
function setWrap(){const value=wrapToggle.checked?'pre-wrap':'pre';codeInput.style.whiteSpace=value;output.style.whiteSpace=value;}
function swap(){const input=codeInput.value;codeInput.value=output.value;output.value=input;fileName.textContent='No file selected';process();}
function clearAll(){codeInput.value='';output.value='';fileName.textContent='No file selected';stats.textContent='Ready';process();}
loadLanguages();setWrap();codeInput.addEventListener('input',process);languageSelect.addEventListener('change',process);whitespaceToggle.addEventListener('change',process);wrapToggle.addEventListener('change',setWrap);document.querySelector('#uploadButton').addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)readFile(file);});codeInput.addEventListener('dragover',e=>{e.preventDefault();codeInput.classList.add('drag');});codeInput.addEventListener('dragleave',()=>codeInput.classList.remove('drag'));codeInput.addEventListener('drop',e=>{e.preventDefault();codeInput.classList.remove('drag');const file=e.dataTransfer.files?.[0];if(file)readFile(file);});copyInputButton.addEventListener('click',()=>copyText(codeInput.value,copyInputButton,'Copied'));copyButton.addEventListener('click',()=>copyText(output.value,copyButton,'Copied'));downloadButton.addEventListener('click',()=>{const blob=new Blob([output.value],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=fileName.textContent&&fileName.textContent!=='No file selected'?`stripped-${fileName.textContent}`:'stripped-code.txt';link.click();URL.revokeObjectURL(url);});swapButton.addEventListener('click',swap);clearButton.addEventListener('click',clearAll);themeButton.addEventListener('click',()=>{document.body.classList.toggle('dark');themeButton.textContent=document.body.classList.contains('dark')?'Light mode':'Dark mode';});codeInput.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter')process();if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='s'){e.preventDefault();swap();}if(e.ctrlKey&&e.key.toLowerCase()==='d'){e.preventDefault();downloadButton.click();}});process();
